{
 "title": "Security",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "srv-ubuntu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Crontab",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_metrics_crontab{exported_job=\"127.0.1.1\", job=\"pushgateway\"}"
    }
   ]
  },
  {
   "title": "authorized_keys_ssh",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_metrics_ssh{exported_job=\"127.0.1.1\", job=\"pushgateway\"}"
    }
   ]
  },
  {
   "title": "Security Graph",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "\nsecurity_metrics_crontab{exported_job=\"127.0.1.1\", job=\"pushgateway\"}"
    },
    {
     "expr": "\nsecurity_metrics_ssh{exported_job=\"127.0.1.1\", job=\"pushgateway\"}"
    },
    {
     "expr": "\nsecurity_metrics_sshd{exported_job=\"127.0.1.1\", job=\"pushgateway\"}"
    },
    {
     "expr": "\nsecurity_metrics_passwd{exported_job=\"127.0.1.1\", job=\"pushgateway\"}"
    }
   ]
  },
  {
   "title": "sshd_config",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_metrics_sshd{exported_job=\"127.0.1.1\", job=\"pushgateway\"}"
    }
   ]
  },
  {
   "title": "passwd",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_metrics_passwd{exported_job=\"127.0.1.1\", job=\"pushgateway\"}"
    }
   ]
  },
  { "title": "srv-backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Crontab",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_metrics_crontab{exported_job=\"192.168.124.51\", job=\"pushgateway\"}"
    }
   ]
  },
  {
   "title": "authorized_keys_ssh",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_metrics_ssh{exported_job=\"192.168.124.51\", job=\"pushgateway\"}"
    }
   ]
  },
  {
   "title": "Security Graph",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "\nsecurity_metrics_crontab{exported_job=\"192.168.124.51\", job=\"pushgateway\"}"
    },
    {
     "expr": "\nsecurity_metrics_ssh{exported_job=\"192.168.124.51\", job=\"pushgateway\"}"
    },
    {
     "expr": "\nsecurity_metrics_sshd{exported_job=\"192.168.124.51\", job=\"pushgateway\"}"
    },
    {
     "expr": "\nsecurity_metrics_passwd{exported_job=\"192.168.124.51\", job=\"pushgateway\"}"
    }
   ]
  },
  {
   "title": "sshd_config",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_metrics_sshd{exported_job=\"192.168.124.51\", job=\"pushgateway\"}"
    }
   ]
  },
  {
   "title": "passwd",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "security_metrics_passwd{exported_job=\"192.168.124.51\", job=\"pushgateway\"}"
    }
   ]
  }
 ]
}